services:
  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:harshpostgres123@postgres:5432/strokecore
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: strokecore
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: harshpostgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d strokecore"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: